version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 590462123944.dkr.ecr.us-west-1.amazonaws.com
      - REPOSITORY_URI=590462123944.dkr.ecr.us-west-1.amazonaws.com/custom-n8n
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker builder prune -f
      - ls -l 
      - pwd
      - docker build --build-arg N8N_VERSION=1.7.1 -t $REPOSITORY_URI .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"n8n","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > taskdef.json
artifacts:
    files: taskdef.json
